### ISSUE TITLE
war file

### ISSUE THREAD

**Issue by mohitccem** [andrea-patricelli/syncope-docker#1]
Hi ,

Can we use war files generated from debian packages or we have to follow https://cwiki.apache.org/confluence/display/SYNCOPE/Run+Syncope+in+real+environments ??

I created war files using https://cwiki.apache.org/confluence/display/SYNCOPE/Install+Syncope+from+.deb+packages , but enable to load the page localhost:9080/syncope-console/

**Comment by andrea-patricelli** [comment]
Hi,

yes you can use the war files created following the guide at [1] as explained at [2].
[3] explains how to install Syncope from deb packages, no war is mentioned in that guide, it's a different approach.

If you want to use the second method to build Syncope in docker (that uses deb package installation internally) please follow [4]. I strongly recommend this approach.

HTH,
Andrea  

[1] https://cwiki.apache.org/confluence/display/SYNCOPE/Run+Syncope+in+real+environments
[2] https://github.com/andrea-patricelli/syncope-docker/wiki/How-to-start-Syncope-Docker-application#prerequisites
[3] https://cwiki.apache.org/confluence/display/SYNCOPE/Install+Syncope+from+.deb+packages
[4] https://github.com/andrea-patricelli/syncope-docker/wiki/How-to-start-Syncope-Docker-application#run-with-docker-compose

**Comment by mohitccem** [comment]
Hi ,

I am following [4] approach . I got this error after "git fetch; git checkout syncope_docker_deb"

fatal: No remote repository specified.  Please, specify either a URL or a
remote name from which new revisions should be fetched.
error: pathspec 'syncope_docker_deb' did not match any file(s) known to git.

**Comment by andrea-patricelli** [comment]
Have you cloned the repository?

`git clone git@github.com:andrea-patricelli/syncope-docker.git`

or 

`git clone https://github.com/andrea-patricelli/syncope-docker.git`

If so please run `git remote add origin git@github.com:andrea-patricelli/syncope-docker.git`

**Comment by mohitccem** [comment]
Hi , 
I executed the above commands . Now after running "docker build -t syncope-docker ."
I am getting following error : 
Sending build context to Docker daemon 100.9 MB
Step 1 : FROM monsantoco/min-jessie:latest
 ---> e82b9f230290
Step 2 : RUN set -x && apt-get update
 ---> Using cache
 ---> 46e4d0316935
Step 3 : WORKDIR /
 ---> Running in 38235d5388ce
 ---> 4afcf58c2c0b
Removing intermediate container 38235d5388ce
Step 4 : ADD http://it.apache.contactlab.it/syncope/1.2.7/apache-syncope-1.2.7.deb /apache-syncope-1.2.7.deb
**Got HTTP status code >= 400: 404 Not Found**

In this link **it.apache.contactlab.it/syncope/** , version 1.2.8 and 2.0.0 is present. Which one i should use??

**Comment by mohitccem** [comment]
Hi,
I gave as [http://it.apache.contactlab.it/syncope/2.0.0/apache-syncope-2.0.0.deb /](url) , after that its enable to locate : 
Sending build context to Docker daemon 100.9 MB
Step 1 : FROM monsantoco/min-jessie:latest
 ---> e82b9f230290
Step 2 : RUN set -x && apt-get update
 ---> Using cache
 ---> 46e4d0316935
Step 3 : WORKDIR /
 ---> Using cache
 ---> 4afcf58c2c0b
Step 4 : ADD http://it.apache.contactlab.it/syncope/2.0.0/apache-syncope-2.0.0.deb /apache-syncope-2.0.0.deb
Downloading [==================================================>] 61.31 MB/61.31 MB
 ---> 9386d67f3bc9
Removing intermediate container f14e38984464
Step 5 : ADD http://mirrors.muzzy.it/apache/syncope/2.0.0/apache-syncope-console-2.0.0.deb /apache-syncope-console-2.0.0.deb
Downloading [==================================================>] 37.82 MB/37.82 MB
 ---> 62dc188a057b
Removing intermediate container fe6951826036
Step 6 : RUN apt-get  -y install tomcat7 libpostgresql-jdbc-java openjdk-7-jre
 ---> Running in 65bdd60680b8
Reading package lists...
**E: Unable to locate package tomcat7
E: Unable to locate package libpostgresql-jdbc-java
E: Unable to locate package openjdk-7-jre**

**Comment by mohitccem** [comment]
Hi , 
The above error was resolved after adding the proxy settings. I am able to install tomcat7 and libpostgresql-jdbc-java , but it is throwing error for openjdk-7-jre. 

The following packages have unmet dependencies:
 openjdk-7-jre : Depends: libgtk2.0-0 (>= 2.8.0) but it is not going to be installed
                 Depends: libpango-1.0-0 (>= 1.14.0) but it is not going to be installed
                 Depends: libatk-wrapper-java-jni (>= 0.30.4-0ubuntu2) but it is not going to be installed
                 Recommends: libgnome2-0 but it is not going to be installed
                 Recommends: libgnomevfs2-0 but it is not going to be installed

**Comment by andrea-patricelli** [comment]
Hi mohitccem,

it seems that errors are due to factors external than mere Docker configuration. I can only suggest you my working environment: Ubuntu 14.04 LTS ,docker 1.8 and docker-compose 1.7.1. I will let you know if it works with latest OS and docker versions. I need time to check.

HTH,
Andrea

**Comment by mohitccem** [comment]
Hi Andrea ,

I am currently using docker 1.12.1 and docker-compose 1.8 , i will give a try with the above mentioned versions.

Thanks,
Mohit

**Comment by mohitccem** [comment]
Hi Andrea ,

I am using the same version of ubuntu 14.04 LTS and docker 1.8 as suggested by you , but still i am facing the same issue.

**openjdk-7-jre : Depends: libgtk2.0-0 (>= 2.8.0) but it is not going to be installed
                 Depends: libpango-1.0-0 (>= 1.14.0) but it is not going to be installed
                 Depends: libatk-wrapper-java-jni (>= 0.30.4-0ubuntu2) but it is not going to be installed
                 Recommends: libgnome2-0 but it is not going to be installed
                 Recommends: libgnomevfs2-0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.**

There is anything else which i can do to resolve this error. 

Regards,
Mohit

**Comment by andrea-patricelli** [comment]
I have to check, maybe images were updated and some dependency between apt packages have been broken. Stay in touch as soon as I have time I will try to investigate better. If you have any news let me know.
As first step I'll try to recreate image from scratch and check if it works on my machine.

Best regards,
Andre

**Comment by andrea-patricelli** [comment]
P.S An important thing!
I noticed that you tried to download Apache Syncope 2.0.
This compose works only for Syncope 1.2.
I'm goingo to open an issue to support 2.0.

**Comment by mohitccem** [comment]
Thanks Andre

**Comment by andrea-patricelli** [comment]
I just updated url of debs. Please make a pull of the project.

Best regards,
Andrea

**Comment by andrea-patricelli** [comment]
I recreated the image from the Dockerfile (docker 1.12.1 and Ubuntu 16.04) from scratch and all worked well. I had no problems of libraries.
Could you please retry the whole process from scratch? delete images and everything downloaded before.

**Comment by mohitccem** [comment]
Hi ,

I installed everything from the scratch . In script i changed the path of tomcat to **http://ftp.heanet.ie/mirrors/www.apache.org/dist/tomcat/tomcat-8/v8.0.37/bin/** . Now i can build successfully. Need to understand what else is needed for version 2.0.0 .

Regards,
Mohit

**Comment by andrea-patricelli** [comment]
Hi mihitccem,

I'm glad to hear it.
If you want to contribute to 2.0.0 there is an open issue at [1].
We would be happy if you want to contribute :)
ASAP I will create a branch for this starting from syncope_docker_deb.
The idea is to change debs download urls and add eventual changes to prepare env for Syncope 2.0 starting from [2].

[1] https://github.com/andrea-patricelli/syncope-docker/issues/2
[2] https://syncope.apache.org/docs/getting-started.html#debian-packages
