### ISSUE TITLE
Add support for Apache Syncope 2.0 

### ISSUE THREAD

**Issue by andrea-patricelli** [andrea-patricelli/syncope-docker#2]

**Comment by JonPe** [comment]
[Dockerfile.txt](https://github.com/andrea-patricelli/syncope-docker/files/509405/Dockerfile.txt)
Created docker image with  Apache Syncope 2.0 deb packages.  
docker is up. I could access syncope console.

**Comment by andrea-patricelli** [comment]
Hi JonPe,

nice to meet you and well done!
Tomorrow I'll create the 2.0 branch and if you want you can become a contributor of the project or make a pull request ;)
BTW I'll make a test ASAP of your work.
Thank you very much for the support!

Best regards,
Andrea

**Comment by andrea-patricelli** [comment]
@JonPe FYI I created https://github.com/andrea-patricelli/syncope-docker/tree/syncope_2.0_docker_deb

**Comment by andrea-patricelli** [comment]
Hi @JonPe ,
I gave a look to your Dockerfile. If you want to perform deb packages installation you should download them into Dockerfile with the command like in https://github.com/andrea-patricelli/syncope-docker/blob/master/syncope-docker/Dockerfile
it would be better ;)

**Comment by JonPe** [comment]
Thanks Andrea!
I had issue in COPYing or ADDing a file to docker in latest docker version. 
But it works when I copy a folder to docker.

Btw, I would check it again.

**Comment by andrea-patricelli** [comment]
Added support for Syncope 2.0.1 with ba9f2394ff25324118a66af77d7c359615590b00. Improvable, but this issue can be considered fixed
