### ISSUE TITLE
Upgrade docker-compose of 1_2_X to version 2

### ISSUE THREAD

**Issue by andrea-patricelli** [andrea-patricelli/syncope-docker#4]

**Comment by hagzag** [comment]
@andrea-patricelli is this a dead horse ? are you still maintaining this ?

**Comment by andrea-patricelli** [comment]
Hi @hagzag !
It is not a dead horse at all! ;)
I'm still maintaining this project. I had no much time to work with in the past months. But I'm planning to be back quite soon.
